/**
 * Bundle xterm.js into a local ES module, once, and commit the result.
 *
 * The app is served with a strict content-security policy and no network: in
 * development aio rewrites a bare `npm:` specifier to a CDN URL, which the
 * policy blocks — correctly, since an app that fetches its terminal emulator
 * from the internet at runtime is an app that stops working on a train.
 *
 * So the emulator is vendored, the same way its stylesheet is. This script is
 * the record of how: run it after changing the pinned version, and commit what
 * it writes.
 *
 *   deno task vendor:xterm
 *
 * The output is a normal ES module with two named exports, which sidesteps the
 * other problem with these packages — they are CommonJS UMD bundles, and Deno
 * and esbuild disagree about whether the classes arrive on the namespace or on
 * `default`.
 */
import * as esbuild from "esbuild";
import { denoPlugins } from "jsr:@luca/esbuild-deno-loader@0.11.1";

const root = new URL("..", import.meta.url).pathname;
const entry = `${root}scripts/xterm-entry.ts`;
const out = `${root}src/ui/vendor/xterm.js`;

await Deno.writeTextFile(
  entry,
  [
    "// Generated by scripts/vendor-xterm.ts — the entry that names what to keep.",
    'export { Terminal } from "@xterm/xterm";',
    'export { FitAddon } from "@xterm/addon-fit";',
    "",
  ].join("\n"),
);

const result = await esbuild.build({
  plugins: [...denoPlugins({ configPath: `${root}deno.json` })],
  entryPoints: [entry],
  bundle: true,
  format: "esm",
  platform: "browser",
  target: "es2022",
  minify: true,
  legalComments: "inline",
  write: false,
});
await esbuild.stop();

const code = result.outputFiles?.[0]?.text ?? "";
if (code.length < 10_000) {
  console.error("vendor-xterm: that bundle is too small to be xterm.js");
  Deno.exit(1);
}

await Deno.writeTextFile(
  out,
  [
    "// xterm.js, bundled into one ES module. DO NOT EDIT.",
    "//",
    "// Generated by `deno task vendor:xterm` from @xterm/xterm and",
    "// @xterm/addon-fit, both MIT. The licence text is inlined below by the",
    "// bundler. Vendored rather than fetched because this app runs under a",
    "// strict content-security policy and must work with no network.",
    "",
    code,
  ].join("\n"),
);
await Deno.remove(entry);
console.log(`vendor-xterm: wrote ${(code.length / 1024).toFixed(0)} KB`);
